export enum FileModules {
  BASIC_DATA = 'BASIC_DATA',
  ACADEMIC_DATA = 'ACADEMIC_DATA',
  EMPLOYEE_DATA = 'EMPLOYEE_DATA',
  PERSONAL_REFERENCE_DATA = 'PERSONAL_REFERENCE_DATA',
}

export enum FileModuleType {
  MILITARY_BOOK = 'MILITARY_BOOK',
  DOCUMENT_NATIONAL = 'DOCUMENT_NATIONAL',
  RESUME = 'RESUME',
  DIPLOMA = 'DIPLOMA',
  STUDY_TRANSCRIPT = 'STUDY_TRANSCRIPT',
  WORK_CERTIFICATION = 'WORK_CERTIFICATION',
  PERSONAL_REFERENCE = 'PERSONAL_REFERENCE',
}
