export enum FileOperationTypes {
  VISIT_DOMICILIARY_FINAL_CONCEPT = 'VISIT_DOMICILIARY_FINAL_CONCEPT',
  REFERENCING_EMPLOYMENT_FILE = 'REFERENCING_EMPLOYMENT_FILE',
  REFERENCING_ACADEMIC_FILE = 'REFERENCING_ACADEMIC_FILE',
  REFERENCING_REFERENCES_FILE = 'REFERENCING_REFERENCES_FILE',
  BACKGROUND_CHECK_FILE = 'BACKGROUND_CHECK_FILE',
  FINANCIAL_FILE = 'FINANCIAL_FILE',
}
