export enum StudiesStatus {
  UNASSIGNED = 'UNASSIGNED',
  ASSIGNED = 'ASSIGNED',
  IN_PROCESS = 'IN_PROCESS',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RETURNING = 'RETURNING',
  POSTED = 'POSTED',
  CANCELLED = 'CANCELLED',
}
