export class CreateDriverDto {
    CONDUCTOR_ID_TIPOIDENTIFICACION?: number;
    CONDUCTOR_IDENTIFICACION?: string;
    CONDUCTOR_CODCONDUCTOR?: string;
    CONDUCTOR_PRIMERNOMBRE?: string;
    CONDUCTOR_SEGUNDONOMBRE?: string;
    CONDUCTOR_PRIMERAPELLIDO?: string;
    CONDUCTOR_SEGUNDOAPELLIDO?: string;
    CONDUCTOR_ID_RH?: number;
    CONDUCTOR_TELPERSONAL?: string;
    CONDUCTOR_TELCORPORATIVO?: string;
    CONDUCTOR_CORREO?: string;
    CONDUCTOR_ID_CIUDAD?: string;
    CONDUCTOR_PASSWORD?: string;
    CONDUCTOR_FOTO?: string;
    CONDUCTOR_FECINGRESO?: string;
    CONDUCTOR_ESTADO?: string;
}