BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[StudyFinancialAccounts] ALTER COLUMN [rating] NVARCHAR(1000) NULL;

-- AlterTable
ALTER TABLE [dbo].[StudyFinancialData] ALTER COLUMN [behavior] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
